movie_app/urls.py
from django.urls import path
from . import views

app_name = 'movie_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('create_admin/', views.create_admin, name='create_admin'),
    path('add_movie/', views.add_movie, name='add_movie'),
    path('search/', views.search_movies, name='search_movies'),
    path('movie_list/', views.movie_list, name='movie_list'),
    path('registrations/', views.registrations, name='registrations'),
    path('adminpage/', views.admin, name='adminpage'),
    path('update/', views.update, name='update'),
    path('update2/<int:movie_id>/', views.update2, name='update2'),
    path('delete/', views.delete, name='delete'),
    path('add_review/', views.add_review, name='add_review'),
    path('add_review2/<int:movie_id>/', views.add_review2, name='add_review2'),
    path('add_category/', views.add_category, name='add_category'),
    path('delete_category/', views.delete_category, name='delete_category'),
    path('reviews/', views.reviews, name='reviews'),
    path('reviews2/<int:movie_id>/', views.reviews2, name='reviews2'),
    path('commingsoon/', views.commingsoon, name='commingsoon'),
    path('intheater/', views.intheater, name='intheater'),
    path('out_of_theater/', views.out_of_theater, name='out_of_theater'),
    path('category_result/<int:item_id>/', views.category_result, name='category_result'),
    path('trailer/', views.trailer, name='trailer'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('mainadmin/', views.mainadmin, name='mainadmin'),
    path('viewuser/', views.viewuser, name='viewuser'),
    path('deleteuser/', views.deleteuser, name='deleteuser'),
    path('message/<message>/', views.message, name='message'),
    path('messageregister/', views.messageregister, name='messageregister'),

]

movie_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category = models.CharField(max_length=100)
    status = models.CharField(max_length=2,default='a')



    
#britto changes
class Movie(models.Model):
    # name = models.CharField(max_length=255)
    name = models.CharField(max_length=255, default="Untitled Movie")

    actor = models.CharField(max_length=255, default="Unknown")

    # actor = models.CharField(max_length=255)
    description = models.TextField(default="No description available")


    # description = models.TextField()
    # poster = models.ImageField(upload_to='posters/')

    poster = models.ImageField(upload_to='posters/', default="default_poster.jpg")
    ruserid = models.IntegerField(default=None, null=True, blank=True)
    theater = models.CharField(max_length=255, default="Unknown")

    category = models.CharField(max_length=255, default="Unknown")

    rdate = models.DateField(null=True, blank=True)

    trailer_link = models.CharField(max_length=255, default="Unknown")

    status = models.CharField(max_length=2,default='a')

# class Movie(models.Model):
#     pass
    # title = models.CharField(max_length=100)
    # poster = models.ImageField(upload_to='posters/')
    # description = models.TextField()
    # release_date = models.DateField()
    # actors = models.CharField(max_length=255, default='Unknown')
    # actors = models.CharField(max_length=200)
    # category = models.CharField(max_length=50)
    # trailer_link = models.URLField()
    # added_by = models.ForeignKey(User, on_delete=models.CASCADE)

    # def __str__(self):
    #     return self.title

# class Review(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews')
#     text = models.TextField()
#     rating = models.IntegerField()
class Review(models.Model):

    m_id = models.IntegerField(default=None, null=True, blank=True)
    review1 = models.CharField(max_length=20000, default="Unknown")
    rating = models.IntegerField(default=None, null=True, blank=True)



class UserCredentials(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    class Meta:
        db_table = 'movie1'

class Admin(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.username
class registration(models.Model):
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)
    status = models.CharField(max_length=2,default='a')


    

    def __str__(self):
        return self.username

# from django.db import models


# class Movie(models.Model):
#     title = models.CharField(max_length=100)
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#     description = models.TextField()
#     img = models.ImageField(upload_to='gallery')
#     # Add more fields as needed
#
#     def __str__(self):
#         return self.title

templates/add_review.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>MovieHunter</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie6.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <h1 id="logo"><a href="{% url 'movie_app:index' %}">MovieHunter</a></h1>
    <div class="social"> <span>FOLLOW US ON:</span>
      <ul>
        <li><a class="twitter" href="#">twitter</a></li>
        <li><a class="facebook" href="#">facebook</a></li>
        <li><a class="vimeo" href="#">video</a></li>
        <li><a class="rss" href="#">rss</a></li>
      </ul>
    </div>
    <div id="navigation">
      <ul>
        <li><a class="active" href="{% url 'movie_app:index' %}">HOME</a></li>
        <li><a href="{% url 'movie_app:reviews' %}">REVIEW</a></li>
        <!-- <li><a href="#">IN THEATERS</a></li> -->
        <!-- <li><a href="#">COMING SOON</a></li> -->
        <!-- <li><a href="#">CATEGORY</a></li> -->
        <!-- <li><a href="#">TRAILERS</a></li> -->
        <!-- <li><select name="category" id="category" onchange="if (this.value) window.location.href=this.value;">
          <option value="" disabled selected>CATEGORY</option>
          {% for item in category %}
         <option value="{% url 'movie_app:category_result' item.id %}">{{ item.category }}</option>
          {% endfor %}
      </select></li> -->
        <li><a href="{% url 'movie_app:login' %}">REGISTER/LOGIN</a></li>
        <!-- <li><a href="{% url 'movie_app:add_movie' %}">ADD MOVIES</a></li> -->


      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <!-- <li><a href="#">SHOW ALL</a></li> -->
        <li><a href="{% url 'movie_app:trailer' %}">LATEST TRAILERS</a></li>
        <li><a href="{% url 'movie_app:commingsoon' %}">COMMING SOON</a></li>
        <li><a href="{% url 'movie_app:intheater' %}">IN THEATER</a></li>
        <li><a href="{% url 'movie_app:out_of_theater' %}">OUT OF THEATER</a></li>

      </ul>
      <div id="search">
        <form method="GET" action="{% url 'movie_app:search_movies' %}" accept-charset="utf-8">
          <label for="search-field">SEARCH</label>
          <input type="text" name="q" value="" id="search-field" class="blink search-field"  />
          <input type="submit" value="GO!" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h2>LATEST TRAILERS</h2>
          <p class="text-right"><a href="#">See all</a></p>
        </div>



        {% for movie in movies %}

        <div class="movie">
            <div class="movie-image"> <span class="play"><span class="name">{{ movie.name }}</span></span> <a href="#"><img src="{{ movie.poster.url }}" alt="{{ movie.name }}"></a> </div>
            <p class="name">{{ movie.name }}</p>
            <p class="name">{{ movie.actor }}</p>
            <p class="name">{{ movie.description}}</p>
            <p><a href="{% url 'movie_app:add_review2' movie.id %}"><button type="submit" name="m_id" value="{{ movie.id }}">ADD REVIEW</button></a></p>
            <div class="rating">
              <p>RATING</p>
              <div class="stars">
                <div class="stars-in"> </div>
              </div>
              <span class="comments">12</span> </div>
          </div>
          {% endfor %}



        <div class="cl">&nbsp;</div>
    </div>
    <div id="footer">
      <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
      <p class="rf">Design by <a href="http://chocotemplates.com/">ChocoTemplates.com</a></p>
      <div style="clear:both;"></div>
    </div>
    </div>
    <!-- END PAGE SOURCE -->
    </body>
    </html>

templates/add_review2.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>MovieHunter</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie6.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <h1 id="logo"><a href="{% url 'movie_app:index' %}">MovieHunter</a></h1>
    <div class="social"> <span>FOLLOW US ON:</span>
      <ul>
        <li><a class="twitter" href="#">twitter</a></li>
        <li><a class="facebook" href="#">facebook</a></li>
        <li><a class="vimeo" href="#">video</a></li>
        <li><a class="rss" href="#">rss</a></li>
      </ul>
    </div>
    <div id="navigation">
      <ul>
        <li><a class="active" href="{% url 'movie_app:index' %}">HOME</a></li>
        <li><a href="{% url 'movie_app:reviews' %}">REVIEW</a></li>
        <!-- <li><a href="#">IN THEATERS</a></li> -->
        <!-- <li><a href="#">COMING SOON</a></li> -->
        <!-- <li><a href="#">CATEGORY</a></li> -->
        <!-- <li><a href="#">TRAILERS</a></li> -->
        <!-- <li><select name="category" id="category" onchange="if (this.value) window.location.href=this.value;">
          <option value="" disabled selected>CATEGORY</option>
          {% for item in category %}
         <option value="{% url 'movie_app:category_result' item.id %}">{{ item.category }}</option>
          {% endfor %}
      </select></li> -->
        <li><a href="{% url 'movie_app:login' %}">REGISTER/LOGIN</a></li>
        <!-- <li><a href="{% url 'movie_app:add_movie' %}">ADD MOVIES</a></li> -->


      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <!-- <li><a href="#">SHOW ALL</a></li> -->
        <li><a href="{% url 'movie_app:trailer' %}">LATEST TRAILERS</a></li>
        <li><a href="{% url 'movie_app:commingsoon' %}">COMMING SOON</a></li>
        <li><a href="{% url 'movie_app:intheater' %}">IN THEATER</a></li>
        <li><a href="{% url 'movie_app:out_of_theater' %}">OUT OF THEATER</a></li>

      </ul>
      <div id="search">
        <form method="GET" action="{% url 'movie_app:search_movies' %}" accept-charset="utf-8">
          <label for="search-field">SEARCH</label>
          <input type="text" name="q" value="" id="search-field" class="blink search-field"  />
          <input type="submit" value="GO!" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h2>LATEST TRAILERS</h2>
          <p class="text-right"><a href="#">See all</a></p>
        </div>



        <center><h1>UPDATE MOVIES</h1></center>
        <form method="post" enctype="multipart/form-data" >
          {% csrf_token %}
          <table>
           
        <tr><td>
          <label for="id_actor">Rating</label></td><td>
          <input type="text" id="id_actor" name="rating" maxlength="100"   required></td>
        </tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td>
          <label for="id_description">Description:</label></td>
          <td>
          <textarea id="id_description" name="review"    required></textarea></td>
        </tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        
    </td></tr><br>
      <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td>
         
          <button type="submit">Submit</button></td></tr>
        </table>
      </form>
  





        <div class="cl">&nbsp;</div>
    </div>
    <div id="footer">
      <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
      <p class="rf">Design by <a href="http://chocotemplates.com/">ChocoTemplates.com</a></p>
      <div style="clear:both;"></div>
    </div>
    </div>
    <!-- END PAGE SOURCE -->
    </body>
    </html>

templates/adminlogin.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>MovieHunter</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie6.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <h1 id="logo"><a href="{% url 'movie_app:index' %}">MovieHunter</a></h1>
    <div class="social"> <span>FOLLOW US ON:</span>
      <ul>
        <li><a class="twitter" href="#">twitter</a></li>
        <li><a class="facebook" href="#">facebook</a></li>
        <li><a class="vimeo" href="#">video</a></li>
        <li><a class="rss" href="#">rss</a></li>
      </ul>
    </div>
    <div id="navigation">
      <ul>
        <li><a class="active" href="{% url 'movie_app:index' %}">HOME</a></li>
        <li><a href="{% url 'movie_app:reviews' %}">REVIEW</a></li>
        <!-- <li><a href="#">IN THEATERS</a></li> -->
        <!-- <li><a href="#">COMING SOON</a></li> -->
        <!-- <li><a href="#">CATEGORY</a></li> -->
        <!-- <li><a href="#">TRAILERS</a></li> -->
        <!-- <li><select name="category" id="category" onchange="if (this.value) window.location.href=this.value;">
          <option value="" disabled selected>CATEGORY</option>
          {% for item in category %}
         <option value="{% url 'movie_app:category_result' item.id %}">{{ item.category }}</option>
          {% endfor %}
      </select></li> -->
        <li><a href="{% url 'movie_app:login' %}">REGISTER/LOGIN</a></li>
        <!-- <li><a href="{% url 'movie_app:add_movie' %}">ADD MOVIES</a></li> -->


      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <!-- <li><a href="#">SHOW ALL</a></li> -->
        <li><a href="{% url 'movie_app:trailer' %}">LATEST TRAILERS</a></li>
        <li><a href="{% url 'movie_app:commingsoon' %}">COMMING SOON</a></li>
        <li><a href="{% url 'movie_app:intheater' %}">IN THEATER</a></li>
        <li><a href="{% url 'movie_app:out_of_theater' %}">OUT OF THEATER</a></li>

      </ul>
      <div id="search">
        <form method="GET" action="{% url 'movie_app:search_movies' %}" accept-charset="utf-8">
          <label for="search-field">SEARCH</label>
          <input type="text" name="q" value="" id="search-field" class="blink search-field"  />
          <input type="submit" value="GO!" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h2>LATEST TRAILERS</h2>
          <p class="text-right"><a href="#">See all</a></p>
        </div>


<form action="/admin_login/" method="post" >
  <table>
{% csrf_token %}
<tr><td></td><td><h1>LOGIN</h1></td></tr>
<tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr><tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr><tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
<tr><td>
    <h4> Username</h4></td><td><input type="text" name="username" placeholder="Enter your  username"></td><br></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td><h4>Password</h4></td><td><input type="password" name="password" placeholder="Enter the password"></td><br></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td></td></tr>
    <tr><td><input type="submit"></td></tr>
{% if message %}
<p>{{ message }}</p>
{% endif %}
</form>

</table>
<table>

<!-- <tr><td>If you don't have account <a href="{% url 'movie_app:registrations' %}"><button type="button">REGISTER</button></a></td></tr> -->

<!-- <tr><td>Admin login <a href="{% url 'movie_app:registrations' %}"><button type="button">ADMIN LOGIN</button></a></td></tr> -->


</table>
<div class="cl">&nbsp;</div>
</div>
<div id="footer">
  <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
  <p class="rf">Design by <a href="http://chocotemplates.com/">ChocoTemplates.com</a></p>
  <div style="clear:both;"></div>
</div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

templates/login.html
<!-- Your template, where you want to display the search results or use the search query -->
<!-- For demonstration, we'll just display the search query -->
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>MovieHunter</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie6.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <h1 id="logo"><a href="#">MovieHunter</a></h1>
    <div class="social"> <span>FOLLOW US ON:</span>
      <ul>
        <li><a class="twitter" href="#">twitter</a></li>
        <li><a class="facebook" href="#">facebook</a></li>
        <li><a class="vimeo" href="#">vimeo</a></li>
        <li><a class="rss" href="#">rss</a></li>
      </ul>
    </div>
    <div id="navigation">
      <ul>
        <li><a class="active" href="#">HOME</a></li>
        <li><a href="#">NEWS</a></li>
        <li><a href="#">IN THEATERS</a></li>
        <li><a href="#">COMING SOON</a></li>
        <li><a href="#">CONTACT</a></li>
        <li><a href="#">ADVERTISE</a></li>
        <li><a href="{% url 'movie_app:login' %}">LOGIN</a></li>

      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <li><a href="#">SHOW ALL</a></li>
        <li><a href="#">LATEST TRAILERS</a></li>
        <li><a href="#">TOP RATED</a></li>
        <li><a href="#">MOST COMMENTED</a></li>
      </ul>
      <div id="search">
        <form action="{% url 'movie_app:search_movies' %}" method="GET" accept-charset="utf-8">
          <label for="search-field">SEARCH</label>
          <input type="text" name="search_field" value="Enter search here" id="search-field" class="blink search-field"  />
          <input type="submit" value="GO!" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h2>LATEST TRAILERS</h2>
          <p class="text-right"><a href="#">See all</a></p>
        </div>



<form action="/login/" method="post" >
  <table>
{% csrf_token %}
    Username<input type="text" name="username" placeholder="Enter your  username"><br>
    Password<input type="password" name="password" placeholder="Enter the password"><br>
    <input type="submit">
</form>
{% if message %}
<p>{{ message }}</p>
{% endif %}
</table>
<div class="cl">&nbsp;</div>
</div>
<div id="footer">
  <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
  <p class="rf">Design by <a href="http://chocotemplates.com/">ChocoTemplates.com</a></p>
  <div style="clear:both;"></div>
</div>
</div>
<!-- END PAGE SOURCE -->
</body>
</html>

templates/update2.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>MovieHunter</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/ie6.css' %}" type="text/css" media="all" />
</head>
<body>
<!-- START PAGE SOURCE -->
<div id="shell">
  <div id="header">
    <h1 id="logo"><a href="{% url 'movie_app:index' %}">MovieHunter</a></h1>
    <div class="social"> <span>FOLLOW US ON:</span>
      <ul>
        <li><a class="twitter" href="#">twitter</a></li>
        <li><a class="facebook" href="#">facebook</a></li>
        <li><a class="vimeo" href="#">video</a></li>
        <li><a class="rss" href="#">rss</a></li>
      </ul>
    </div>
    <div id="navigation">
      <ul>
        <li><a class="active" href="{% url 'movie_app:index' %}">HOME</a></li>
        <li><a href="{% url 'movie_app:reviews' %}">REVIEW</a></li>
        <!-- <li><a href="#">IN THEATERS</a></li> -->
        <!-- <li><a href="#">COMING SOON</a></li> -->
        <!-- <li><a href="#">CATEGORY</a></li> -->
        <!-- <li><a href="#">TRAILERS</a></li> -->
        <!-- <li><select name="category" id="category" onchange="if (this.value) window.location.href=this.value;">
          <option value="" disabled selected>CATEGORY</option>
          {% for item in category %}
         <option value="{% url 'movie_app:category_result' item.id %}">{{ item.category }}</option>
          {% endfor %}
      </select></li> -->
        <li><a href="{% url 'movie_app:login' %}">REGISTER/LOGIN</a></li>
        <!-- <li><a href="{% url 'movie_app:add_movie' %}">ADD MOVIES</a></li> -->


      </ul>
    </div>
    <div id="sub-navigation">
      <ul>
        <!-- <li><a href="#">SHOW ALL</a></li> -->
        <li><a href="{% url 'movie_app:trailer' %}">LATEST TRAILERS</a></li>
        <li><a href="{% url 'movie_app:commingsoon' %}">COMMING SOON</a></li>
        <li><a href="{% url 'movie_app:intheater' %}">IN THEATER</a></li>
        <li><a href="{% url 'movie_app:out_of_theater' %}">OUT OF THEATER</a></li>

      </ul>
      <div id="search">
        <form method="GET" action="{% url 'movie_app:search_movies' %}" accept-charset="utf-8">
          <label for="search-field">SEARCH</label>
          <input type="text" name="q" value="" id="search-field" class="blink search-field"  />
          <input type="submit" value="GO!" class="search-button" />
        </form>
      </div>
    </div>
  </div>
  <div id="main">
    <div id="content">
      <div class="box">
        <div class="head">
          <h2>LATEST TRAILERS</h2>
          <p class="text-right"><a href="#">See all</a></p>
        </div>



        <center><h1>UPDATE MOVIES</h1></center>
        <form method="post" enctype="multipart/form-data" >
          {% csrf_token %}
          <table>
            <tr><td>
          <label for="id_name">Name:</label></td>
          <td>
          <input type="text" id="id_name" name="name" maxlength="100" value="{{ movie.name }}" required></td>
        </tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
  
        <tr><td>
          <label for="id_actor">Actor:</label></td><td>
          <input type="text" id="id_actor" name="actor" maxlength="100"  value="{{ movie.actor }}" required></td>
        </tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td>
          <label for="id_description">Description:</label></td>
          <td>
          <textarea id="id_description" name="description"    required>{{ movie.description}}</textarea></td>
        </tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td>
          <label for="id_poster">Poster:</label></td><td>
          <input type="file" id="id_poster" name="poster"  accept="image/*" required></td>
        </tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td><label for="id_poster" >Status</label></td><td>
        <select id="theater" name="theater"  value="{{ movie.status }}">
          <option value="CS">Coming Soon</option>
          <option value="IT">In Theater</option>
          <option value="OT">Out of Theater</option>
      </select>
    </td></tr><br>
      <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td></td></tr>
        <tr><td>
         
          <button type="submit">Submit</button></td></tr>
        </table>
      </form>
  





        <div class="cl">&nbsp;</div>
    </div>
    <div id="footer">
      <p class="lf">Copyright &copy; 2010 <a href="#">SiteName</a> - All Rights Reserved</p>
      <p class="rf">Design by <a href="http://chocotemplates.com/">ChocoTemplates.com</a></p>
      <div style="clear:both;"></div>
    </div>
    </div>
    <!-- END PAGE SOURCE -->
    </body>
    </html>